# Generated by Django 3.0.7 on 2020-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attribute',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
