# Generated by Django 3.0.7 on 2020-06-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardapp', '0002_auto_20200617_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
