# Generated by Django 3.0.7 on 2020-06-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardapp', '0003_auto_20200619_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='notes',
            new_name='set_notes',
        ),
    ]
