# Generated by Django 3.0.7 on 2020-06-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardapp', '0004_auto_20200619_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='set_notes',
            new_name='setnotes',
        ),
    ]
