# Generated by Django 3.0.7 on 2020-06-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardapp', '0006_auto_20200619_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='playerId_id',
            new_name='playerId',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='setId_id',
            new_name='setId',
        ),
    ]
