from baseballcardapp.views.auth.logout import logout_user
from .connection import Connection
from .home import home
from .main.list import main
from .auth.register import register_form
from .players.list import *
from .players.form import player_form
from .players.details import player_details
from .sets.list import set_list
from .sets.form import set_form
from .sets.details import set_details
from .collection.list import collection_list
from .cards.list import card_list
from .cards.form import card_form
